apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sql-deployment-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-app
  minReplicas: 1
  maxReplicas: 10
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 180  # 3분 동안의 데이터를 사용해서 스케일 다운
      policies:
        - type: Pods
          value: 1                      # 한 번에 스케일 다운할 수 있는 최대 파드 수
          periodSeconds: 60             # 스케일 다운 사이의 최소 시간 간격
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 20
