apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: filestore-sc
provisioner: filestore.csi.storage.gke.io
#reclaimPolicy: Delete                     # pv 삭제
#reclaimPolicy: Retain                     # pv 및 파일 유지
#reclaimPolicy: Recycle                    # pv 삭제
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
  tier: standard
  network: default

