apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dasc-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: filestore-sc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dasc-deployment
  labels:
    app: rds-deployment-hpa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dasc-deployment
  template:
    metadata:
      labels:
        app: dasc-deployment
    spec:
      containers:
      - name: rds-deployment
        image: gcr.io/healthy-garage-432208-u0/rds-was
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 20m
          limits:
            cpu: 50m
        volumeMounts:
        - mountPath: "/var/www/html"
          name: pvc-vol
      volumes:
      - name: pvc-vol
        persistentVolumeClaim:
          claimName: dasc-pvc

