apiVersion: v1
kind: ConfigMap
metadata:
  name: rds-config
data:
  DB_HOST: jhtest.ctm8u66282ry.ap-northeast-2.rds.amazonaws.com
  DB_NAME: exam_system
  DB_USER: admin
  DB_PASSWORD: dkagh1.!
  DB_CHARSET: utf8mb4
  ---
  apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-config
data:
  apache2.conf: |
    ServerName localhost

    <Directory /var/www/html/>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    DirectoryIndex index.php index.html
